version: "3.8"
   
services:
  fincalcs:
    container_name: fincalcs_service
    build: .
    ports:
      - "8001:8001"
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - invest-system
  mongodb:
    image: mongo:4.4-bionic
    container_name: fincalcs_mongodb
    environment:
      - 'MONGODB_USER=fincalcs'
      - 'MONGODB_PASS=fincalcspass'
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongo-configdb:/data/configdb
    networks:
      - invest-system

volumes:
  mongodata:
  mongo-configdb:

networks:
  invest-system:
    external: true
